name: GodFather_Final_Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # استخدمنا أكشن مختلف تماماً عشان نهرب من الـ Error القديم
        uses: pypa/gh-action-pypi-publish@release/v1
        continue-on-error: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-setuptools colorama appdirs
          pip3 install --user --upgrade buildozer

      - name: Run Buildozer
        run: buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Premium_App
          path: bin/*.apk
