name: Build and Deploy D3f4ult

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          # تم تحديث المكتبات لتتوافق مع نسخة Ubuntu الحديثة وحذف libtinfo5 المسببة للخطأ
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev openjdk-17-jdk
          pip install buildozer cython==0.29.33

      - name: Build APK (The Shadow Factory)
        run: |
          [ -f buildozer.spec ] || buildozer init
          # بناء التطبيق وتجاهل التحذيرات غير المؤثرة
          yes | buildozer -v android debug || true

      - name: Shadow Core Finder (The Hunt)
        run: |
          # إنشاء مجلد نهائي لتجميع الملفات فيه
          mkdir -p final_artifacts
          # البحث في كل السيرفر عن أي ملف APK تم إنتاجه ونقله للمجلد
          find . -name "*.apk" -exec cp {} final_artifacts/D3f4ult_Shadow.apk \;
          echo "Shadow Core: APK has been captured and moved."

      - name: Upload Final Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Shadow-Core-App
          path: final_artifacts/
